# -*- encoding: utf-8 -*-

=begin
#OneSignal

#A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com

The version of the OpenAPI document: 1.4.1
Contact: devrel@onesignal.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.0-SNAPSHOT

=end

$:.push File.expand_path("../lib", __FILE__)
require "onesignal/version"

Gem::Specification.new do |s|
  s.name        = "onesignal"
  s.version     = OneSignal::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["OneSignal"]
  s.email       = ["devrel@onesignal.com"]
  s.homepage    = "https://onesignal.com/"
  s.summary     = "OneSignal"
  s.description = "OneSignal"
  s.license     = "Modified MIT"
  s.required_ruby_version = ">= 2.4"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
