=begin
#OneSignal

#A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com

The version of the OpenAPI document: 5.2.1
Contact: devrel@onesignal.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.0-SNAPSHOT

=end

require 'date'
require 'time'

module OneSignal
  class NotificationWithMeta
    # The segment names you want to target. Users in these segments will receive a notification. This targeting parameter is only compatible with excluded_segments. Example: [\"Active Users\", \"Inactive Users\"] 
    attr_accessor :included_segments

    # Segment that will be excluded when sending. Users in these segments will not receive a notification, even if they were included in included_segments. This targeting parameter is only compatible with included_segments. Example: [\"Active Users\", \"Inactive Users\"] 
    attr_accessor :excluded_segments

    # Specific subscription ids to send your notification to. _Does not require API Auth Key._ Not compatible with any other targeting parameters. Example: [\"1dd608f2-c6a1-11e3-851d-000c2940e62c\"] Limit of 2,000 entries per REST API call 
    attr_accessor :include_subscription_ids

    # Recommended for Sending Emails - Target specific email addresses. If an email does not correspond to an existing user, a new user will be created. Example: nick@catfac.ts Limit of 2,000 entries per REST API call 
    attr_accessor :include_email_tokens

    # Recommended for Sending SMS - Target specific phone numbers. The phone number should be in the E.164 format. Phone number should be an existing subscriber on OneSignal. Refer our docs to learn how to add phone numbers to OneSignal. Example phone number: +1999999999 Limit of 2,000 entries per REST API call 
    attr_accessor :include_phone_numbers

    # Not Recommended: Please consider using include_subscription_ids or include_aliases instead. Target using iOS device tokens. Warning: Only works with Production tokens. All non-alphanumeric characters must be removed from each token. If a token does not correspond to an existing user, a new user will be created. Example: ce777617da7f548fe7a9ab6febb56cf39fba6d38203... Limit of 2,000 entries per REST API call 
    attr_accessor :include_ios_tokens

    # Not Recommended: Please consider using include_subscription_ids or include_aliases instead. Target using Windows URIs. If a token does not correspond to an existing user, a new user will be created. Example: http://s.notify.live.net/u/1/bn1/HmQAAACPaLDr-... Limit of 2,000 entries per REST API call 
    attr_accessor :include_wp_wns_uris

    # Not Recommended: Please consider using include_subscription_ids or include_aliases instead. Target using Amazon ADM registration IDs. If a token does not correspond to an existing user, a new user will be created. Example: amzn1.adm-registration.v1.XpvSSUk0Rc3hTVVV... Limit of 2,000 entries per REST API call 
    attr_accessor :include_amazon_reg_ids

    # Not Recommended: Please consider using include_subscription_ids or include_aliases instead. Target using Chrome App registration IDs. If a token does not correspond to an existing user, a new user will be created. Example: APA91bEeiUeSukAAUdnw3O2RB45FWlSpgJ7Ji_... Limit of 2,000 entries per REST API call 
    attr_accessor :include_chrome_reg_ids

    # Not Recommended: Please consider using include_subscription_ids or include_aliases instead. Target using Chrome Web Push registration IDs. If a token does not correspond to an existing user, a new user will be created. Example: APA91bEeiUeSukAAUdnw3O2RB45FWlSpgJ7Ji_... Limit of 2,000 entries per REST API call 
    attr_accessor :include_chrome_web_reg_ids

    # Not Recommended: Please consider using include_subscription_ids or include_aliases instead. Target using Android device registration IDs. If a token does not correspond to an existing user, a new user will be created. Example: APA91bEeiUeSukAAUdnw3O2RB45FWlSpgJ7Ji_... Limit of 2,000 entries per REST API call 
    attr_accessor :include_android_reg_ids

    # Target specific users by aliases assigned via API. An alias can be an external_id, onesignal_id, or a custom alias. Accepts an object where keys are alias labels and values are arrays of alias IDs to include Example usage: { \"external_id\": [\"exId1\", \"extId2\"], \"internal_label\": [\"id1\", \"id2\"] } Not compatible with any other targeting parameters. REQUIRED: REST API Key Authentication Limit of 2,000 entries per REST API call Note: If targeting push, email, or sms subscribers with same ids, use with target_channel to indicate you are sending a push or email or sms.
    attr_accessor :include_aliases

    attr_accessor :target_channel

    attr_accessor :id

    attr_accessor :value

    # Required for SMS Messages. An identifier for tracking message within the OneSignal dashboard or export analytics. Not shown to end user.
    attr_accessor :name

    attr_accessor :aggregation

    # Indicates whether to send to all devices registered under your app's Apple iOS platform.
    attr_accessor :is_ios

    # Indicates whether to send to all devices registered under your app's Google Android platform.
    attr_accessor :is_android

    # Indicates whether to send to all devices registered under your app's Huawei Android platform.
    attr_accessor :is_huawei

    # Indicates whether to send to all subscribed web browser users, including Chrome, Firefox, and Safari. You may use this instead as a combined flag instead of separately enabling isChromeWeb, isFirefox, and isSafari, though the three options are equivalent to this one. 
    attr_accessor :is_any_web

    # Indicates whether to send to all Google Chrome, Chrome on Android, and Mozilla Firefox users registered under your Chrome & Firefox web push platform.
    attr_accessor :is_chrome_web

    # Indicates whether to send to all Mozilla Firefox desktop users registered under your Firefox web push platform.
    attr_accessor :is_firefox

    # Does not support iOS Safari. Indicates whether to send to all Apple's Safari desktop users registered under your Safari web push platform. Read more iOS Safari
    attr_accessor :is_safari

    # Indicates whether to send to all devices registered under your app's Windows platform.
    attr_accessor :is_wp_wns

    # Indicates whether to send to all devices registered under your app's Amazon Fire platform.
    attr_accessor :is_adm

    # This flag is not used for web push Please see isChromeWeb for sending to web push users. This flag only applies to Google Chrome Apps & Extensions. Indicates whether to send to all devices registered under your app's Google Chrome Apps & Extension platform. 
    attr_accessor :is_chrome

    # Required: Your OneSignal Application ID, which can be found in Keys & IDs. It is a UUID and looks similar to 8250eaf6-1a58-489e-b136-7c74a864b434. 
    attr_accessor :app_id

    # [DEPRECATED] Correlation and idempotency key. A request received with this parameter will first look for another notification with the same external_id. If one exists, a notification will not be sent, and result of the previous operation will instead be returned. Therefore, if you plan on using this feature, it's important to use a good source of randomness to generate the UUID passed here. This key is only idempotent for 30 days. After 30 days, the notification could be removed from our system and a notification with the same external_id will be sent again.   See Idempotent Notification Requests for more details writeOnly: true 
    attr_accessor :external_id

    # Correlation and idempotency key. A request received with this parameter will first look for another notification with the same idempotency key. If one exists, a notification will not be sent, and result of the previous operation will instead be returned. Therefore, if you plan on using this feature, it's important to use a good source of randomness to generate the UUID passed here. This key is only idempotent for 30 days. After 30 days, the notification could be removed from our system and a notification with the same idempotency key will be sent again.   See Idempotent Notification Requests for more details writeOnly: true 
    attr_accessor :idempotency_key

    attr_accessor :contents

    attr_accessor :headings

    attr_accessor :subtitle

    # Channel: Push Notifications Platform: Huawei A custom map of data that is passed back to your app. Same as using Additional Data within the dashboard. Can use up to 2048 bytes of data. Example: {\"abc\": 123, \"foo\": \"bar\", \"event_performed\": true, \"amount\": 12.1} 
    attr_accessor :data

    # Channel: Push Notifications Platform: Huawei Use \"data\" or \"message\" depending on the type of notification you are sending. More details in Data & Background Notifications. 
    attr_accessor :huawei_msg_type

    # Channel: Push Notifications Platform: All The URL to open in the browser when a user clicks on the notification. Note: iOS needs https or updated NSAppTransportSecurity in plist This field supports inline substitutions. Omit if including web_url or app_url Example: https://onesignal.com 
    attr_accessor :url

    # Channel: Push Notifications Platform: All Browsers Same as url but only sent to web push platforms. Including Chrome, Firefox, Safari, Opera, etc. Example: https://onesignal.com 
    attr_accessor :web_url

    # Channel: Push Notifications Platform: All Browsers Same as url but only sent to web push platforms. Including iOS, Android, macOS, Windows, ChromeApps, etc. Example: https://onesignal.com 
    attr_accessor :app_url

    # Channel: Push Notifications Platform: iOS 10+ Adds media attachments to notifications. Set as JSON object, key as a media id of your choice and the value as a valid local filename or URL. User must press and hold on the notification to view. Do not set mutable_content to download attachments. The OneSignal SDK does this automatically Example: {\"id1\": \"https://domain.com/image.jpg\"} 
    attr_accessor :ios_attachments

    # Channel: Push Notifications Platform: All Use a template you setup on our dashboard. The template_id is the UUID found in the URL when viewing a template on our dashboard. Example: be4a8044-bbd6-11e4-a581-000c2940e62c 
    attr_accessor :template_id

    # Channel: Push Notifications Platform: iOS Sending true wakes your app from background to run custom native code (Apple interprets this as content-available=1). Note: Not applicable if the app is in the \"force-quit\" state (i.e app was swiped away). Omit the contents field to prevent displaying a visible notification. 
    attr_accessor :content_available

    # Channel: Push Notifications Platform: iOS 10+ Always defaults to true and cannot be turned off. Allows tracking of notification receives and changing of the notification content in your app before it is displayed. Triggers didReceive(_:withContentHandler:) on your UNNotificationServiceExtension. 
    attr_accessor :mutable_content

    # Channel: Push Notifications Platform: iOS 13+ Use to target a specific experience in your App Clip, or to target your notification to a specific window in a multi-scene App. 
    attr_accessor :target_content_identifier

    # Channel: Push Notifications Platform: Android Picture to display in the expanded view. Can be a drawable resource name or a URL. 
    attr_accessor :big_picture

    # Channel: Push Notifications Platform: Huawei Picture to display in the expanded view. Can be a drawable resource name or a URL. 
    attr_accessor :huawei_big_picture

    # Channel: Push Notifications Platform: Amazon Picture to display in the expanded view. Can be a drawable resource name or a URL. 
    attr_accessor :adm_big_picture

    # Channel: Push Notifications Platform: ChromeApp Large picture to display below the notification text. Must be a local URL. 
    attr_accessor :chrome_big_picture

    # Channel: Push Notifications Platform: Chrome 56+ Sets the web push notification's large image to be shown below the notification's title and text. Please see Web Push Notification Icons. 
    attr_accessor :chrome_web_image

    # Channel: Push Notifications Platform: iOS 8.0+, Android 4.1+, and derivatives like Amazon Buttons to add to the notification. Icon only works for Android. Buttons show in reverse order of array position i.e. Last item in array shows as first button on device. Example: [{\"id\": \"id2\", \"text\": \"second button\", \"icon\": \"ic_menu_share\"}, {\"id\": \"id1\", \"text\": \"first button\", \"icon\": \"ic_menu_send\"}] 
    attr_accessor :buttons

    # Channel: Push Notifications Platform: Chrome 48+ Add action buttons to the notification. The id field is required. Example: [{\"id\": \"like-button\", \"text\": \"Like\", \"icon\": \"http://i.imgur.com/N8SN8ZS.png\", \"url\": \"https://yoursite.com\"}, {\"id\": \"read-more-button\", \"text\": \"Read more\", \"icon\": \"http://i.imgur.com/MIxJp1L.png\", \"url\": \"https://yoursite.com\"}] 
    attr_accessor :web_buttons

    # Channel: Push Notifications Platform: iOS Category APS payload, use with registerUserNotificationSettings:categories in your Objective-C / Swift code. Example: calendar category which contains actions like accept and decline iOS 10+ This will trigger your UNNotificationContentExtension whose ID matches this category. 
    attr_accessor :ios_category

    # Channel: Push Notifications Platform: Android The Android Oreo Notification Category to send the notification under. See the Category documentation on creating one and getting it's id. 
    attr_accessor :android_channel_id

    # Channel: Push Notifications Platform: Huawei The Android Oreo Notification Category to send the notification under. See the Category documentation on creating one and getting it's id. 
    attr_accessor :huawei_channel_id

    # Channel: Push Notifications Platform: Android Use this if you have client side Android Oreo Channels you have already defined in your app with code. 
    attr_accessor :existing_android_channel_id

    # Channel: Push Notifications Platform: Huawei Use this if you have client side Android Oreo Channels you have already defined in your app with code. 
    attr_accessor :huawei_existing_channel_id

    attr_accessor :android_background_layout

    # Channel: Push Notifications Platform: Android Icon shown in the status bar and on the top left of the notification. If not set a bell icon will be used or ic_stat_onesignal_default if you have set this resource name. See: How to create small icons 
    attr_accessor :small_icon

    # Channel: Push Notifications Platform: Huawei Icon shown in the status bar and on the top left of the notification. Use an Android resource path (E.g. /drawable/small_icon). Defaults to your app icon if not set. 
    attr_accessor :huawei_small_icon

    # Channel: Push Notifications Platform: Android Can be a drawable resource name or a URL. See: How to create large icons 
    attr_accessor :large_icon

    # Channel: Push Notifications Platform: Huawei Can be a drawable resource name or a URL. See: How to create large icons 
    attr_accessor :huawei_large_icon

    # Channel: Push Notifications Platform: Amazon If not set a bell icon will be used or ic_stat_onesignal_default if you have set this resource name. See: How to create small icons 
    attr_accessor :adm_small_icon

    # Channel: Push Notifications Platform: Amazon If blank the small_icon is used. Can be a drawable resource name or a URL. See: How to create large icons 
    attr_accessor :adm_large_icon

    # Channel: Push Notifications Platform: Chrome Sets the web push notification's icon. An image URL linking to a valid image. Common image types are supported; GIF will not animate. We recommend 256x256 (at least 80x80) to display well on high DPI devices. Firefox will also use this icon, unless you specify firefox_icon. 
    attr_accessor :chrome_web_icon

    # Channel: Push Notifications Platform: Chrome Sets the web push notification icon for Android devices in the notification shade. Please see Web Push Notification Badge. 
    attr_accessor :chrome_web_badge

    # Channel: Push Notifications Platform: Firefox Not recommended Few people need to set Firefox-specific icons. We recommend setting chrome_web_icon instead, which Firefox will also use. Sets the web push notification's icon for Firefox. An image URL linking to a valid image. Common image types are supported; GIF will not animate. We recommend 256x256 (at least 80x80) to display well on high DPI devices. 
    attr_accessor :firefox_icon

    # Channel: Push Notifications Platform: ChromeApp This flag is not used for web push For web push, please see chrome_web_icon instead. The local URL to an icon to use. If blank, the app icon will be used. 
    attr_accessor :chrome_icon

    # Channel: Push Notifications Platform: iOS Sound file that is included in your app to play instead of the default device notification sound. Pass nil to disable vibration and sound for the notification. Example: \"notification.wav\" 
    attr_accessor :ios_sound

    # Channel: Push Notifications Platform: Android &#9888;&#65039;Deprecated, this field doesn't work on Android 8 (Oreo) and newer devices! Please use Notification Categories / Channels noted above instead to support ALL versions of Android. Sound file that is included in your app to play instead of the default device notification sound. Pass nil to disable sound for the notification. NOTE: Leave off file extension for Android. Example: \"notification\" 
    attr_accessor :android_sound

    # Channel: Push Notifications Platform: Huawei &#9888;&#65039;Deprecated, this field ONLY works on EMUI 5 (Android 7 based) and older devices. Please also set Notification Categories / Channels noted above to support EMUI 8 (Android 8 based) devices. Sound file that is included in your app to play instead of the default device notification sound. NOTE: Leave off file extension for and include the full path.  Example: \"/res/raw/notification\" 
    attr_accessor :huawei_sound

    # Channel: Push Notifications Platform: Amazon &#9888;&#65039;Deprecated, this field doesn't work on Android 8 (Oreo) and newer devices! Please use Notification Categories / Channels noted above instead to support ALL versions of Android. Sound file that is included in your app to play instead of the default device notification sound. Pass nil to disable sound for the notification. NOTE: Leave off file extension for Android. Example: \"notification\" 
    attr_accessor :adm_sound

    # Channel: Push Notifications Platform: Windows Sound file that is included in your app to play instead of the default device notification sound. Example: \"notification.wav\" 
    attr_accessor :wp_wns_sound

    # Channel: Push Notifications Platform: Android &#9888;&#65039;Deprecated, this field doesn't work on Android 8 (Oreo) and newer devices! Please use Notification Categories / Channels noted above instead to support ALL versions of Android. Sets the devices LED notification light if the device has one. ARGB Hex format. Example(Blue): \"FF0000FF\" 
    attr_accessor :android_led_color

    # Channel: Push Notifications Platform: Huawei &#9888;&#65039;Deprecated, this field ONLY works on EMUI 5 (Android 7 based) and older devices. Please also set Notification Categories / Channels noted above to support EMUI 8 (Android 8 based) devices. Sets the devices LED notification light if the device has one. RGB Hex format. Example(Blue): \"0000FF\" 
    attr_accessor :huawei_led_color

    # Channel: Push Notifications Platform: Android Sets the background color of the notification circle to the left of the notification text. Only applies to apps targeting Android API level 21+ on Android 5.0+ devices. Example(Red): \"FFFF0000\" 
    attr_accessor :android_accent_color

    # Channel: Push Notifications Platform: Huawei Accent Color used on Action Buttons and Group overflow count. Uses RGB Hex value (E.g. #9900FF). Defaults to device's theme color if not set. 
    attr_accessor :huawei_accent_color

    # Channel: Push Notifications Platform: Android 5.0_ &#9888;&#65039;Deprecated, this field doesn't work on Android 8 (Oreo) and newer devices! Please use Notification Categories / Channels noted above instead to support ALL versions of Android. 1 = Public (default) (Shows the full message on the lock screen unless the user has disabled all notifications from showing on the lock screen. Please consider the user and mark private if the contents are.) 0 = Private (Hides message contents on lock screen if the user set \"Hide sensitive notification content\" in the system settings) -1 = Secret (Notification does not show on the lock screen at all) 
    attr_accessor :android_visibility

    # Channel: Push Notifications Platform: Huawei &#9888;&#65039;Deprecated, this field ONLY works on EMUI 5 (Android 7 based) and older devices. Please also set Notification Categories / Channels noted above to support EMUI 8 (Android 8 based) devices. 1 = Public (default) (Shows the full message on the lock screen unless the user has disabled all notifications from showing on the lock screen. Please consider the user and mark private if the contents are.) 0 = Private (Hides message contents on lock screen if the user set \"Hide sensitive notification content\" in the system settings) -1 = Secret (Notification does not show on the lock screen at all) 
    attr_accessor :huawei_visibility

    # Channel: Push Notifications Platform: iOS Describes whether to set or increase/decrease your app's iOS badge count by the ios_badgeCount specified count. Can specify None, SetTo, or Increase. `None` leaves the count unaffected. `SetTo` directly sets the badge count to the number specified in ios_badgeCount. `Increase` adds the number specified in ios_badgeCount to the total. Use a negative number to decrease the badge count. 
    attr_accessor :ios_badge_type

    # Channel: Push Notifications Platform: iOS Used with ios_badgeType, describes the value to set or amount to increase/decrease your app's iOS badge count by. You can use a negative number to decrease the badge count when used with an ios_badgeType of Increase. 
    attr_accessor :ios_badge_count

    # Channel: Push Notifications Platform: iOS 10+, Android Only one notification with the same id will be shown on the device. Use the same id to update an existing notification instead of showing a new one. Limit of 64 characters. 
    attr_accessor :collapse_id

    # Channel: Push Notifications Platform: All Browsers Display multiple notifications at once with different topics. 
    attr_accessor :web_push_topic

    # Channel: Push Notifications Platform: iOS 10+ iOS can localize push notification messages on the client using special parameters such as loc-key. When using the Create Notification endpoint, you must include these parameters inside of a field called apns_alert. Please see Apple's guide on localizing push notifications to learn more. 
    attr_accessor :apns_alert

    # Channel: All Possible values are: timezone (Deliver at a specific time-of-day in each users own timezone) last-active Same as Intelligent Delivery . (Deliver at the same time of day as each user last used your app). If send_after is used, this takes effect after the send_after time has elapsed. 
    attr_accessor :delayed_option

    # Channel: All Use with delayed_option=timezone. Examples: \"9:00AM\" \"21:45\" \"9:45:30\" 
    attr_accessor :delivery_time_of_day

    # Channel: Push Notifications Platform: iOS, Android, Chrome, Firefox, Safari, ChromeWeb Time To Live - In seconds. The notification will be expired if the device does not come back online within this time. The default is 259,200 seconds (3 days). Max value to set is 2419200 seconds (28 days). 
    attr_accessor :ttl

    # Channel: Push Notifications Platform: Android, Chrome, ChromeWeb Delivery priority through the push server (example GCM/FCM). Pass 10 for high priority or any other integer for normal priority. Defaults to normal priority for Android and high for iOS. For Android 6.0+ devices setting priority to high will wake the device out of doze mode. 
    attr_accessor :priority

    # Channel: Push Notifications Platform: iOS valid values: voip Set the value to voip for sending VoIP Notifications This field maps to the APNS header apns-push-type. Note: alert and background are automatically set by OneSignal 
    attr_accessor :apns_push_type_override

    # number of push notifications sent per minute. Paid Feature Only. If throttling is not enabled for the app or the notification, and for free accounts, null is returned. Refer to Throttling for more details.
    attr_accessor :throttle_rate_per_minute

    # Channel: Push Notifications Platform: Android Notifications with the same group will be stacked together using Android's Notification Grouping feature. 
    attr_accessor :android_group

    # Channel: Push Notifications Platform: Android Note: This only works for Android 6 and older. Android 7+ allows full expansion of all message. Summary message to display when 2+ notifications are stacked together. Default is \"# new messages\". Include $[notif_count] in your message and it will be replaced with the current number. Languages - The value of each key is the message that will be sent to users for that language. \"en\" (English) is required. The key of each hash is either a a 2 character language code or one of zh-Hans/zh-Hant for Simplified or Traditional Chinese. Read more: supported languages. Example: {\"en\": \"You have $[notif_count] new messages\"} 
    attr_accessor :android_group_message

    # Channel: Push Notifications Platform: Amazon Notifications with the same group will be stacked together using Android's Notification Grouping feature. 
    attr_accessor :adm_group

    # Channel: Push Notifications Platform: Amazon Summary message to display when 2+ notifications are stacked together. Default is \"# new messages\". Include $[notif_count] in your message and it will be replaced with the current number. \"en\" (English) is required. The key of each hash is either a a 2 character language code or one of zh-Hans/zh-Hant for Simplified or Traditional Chinese. The value of each key is the message that will be sent to users for that language. Example: {\"en\": \"You have $[notif_count] new messages\"} 
    attr_accessor :adm_group_message

    # Channel: Push Notifications Platform: iOS 12+ This parameter is supported in iOS 12 and above. It allows you to group related notifications together. If two notifications have the same thread-id, they will both be added to the same group. 
    attr_accessor :thread_id

    # Channel: Push Notifications Platform: iOS 12+ When using thread_id to create grouped notifications in iOS 12+, you can also control the summary. For example, a grouped notification can say \"12 more notifications from John Doe\". The summary_arg lets you set the name of the person/thing the notifications are coming from, and will show up as \"X more notifications from summary_arg\" 
    attr_accessor :summary_arg

    # Channel: Push Notifications Platform: iOS 12+ When using thread_id, you can also control the count of the number of notifications in the group. For example, if the group already has 12 notifications, and you send a new notification with summary_arg_count = 2, the new total will be 14 and the summary will be \"14 more notifications from summary_arg\" 
    attr_accessor :summary_arg_count

    # Channel: Push Notifications Platform: iOS 15+ A score to be set per notification to indicate how it should be displayed when grouped. Use a float between 0-1. 
    attr_accessor :ios_relevance_score

    # Channel: Push Notifications Platform: iOS 15+ Focus Modes and Interruption Levels indicate the priority and delivery timing of a notification, to \"interrupt\" the user. Can choose from options: ['active', 'passive', 'time_sensitive', 'critical']. Default is active. 
    attr_accessor :ios_interruption_level

    # Channel: Email Required.  The subject of the email. 
    attr_accessor :email_subject

    # Channel: Email Required unless template_id is set. HTML suported The body of the email you wish to send. Typically, customers include their own HTML templates here. Must include [unsubscribe_url] in an <a> tag somewhere in the email. Note: any malformed HTML content will be sent to users. Please double-check your HTML is valid. 
    attr_accessor :email_body

    # Channel: Email The name the email is from. If not specified, will default to \"from name\" set in the OneSignal Dashboard Email Settings. 
    attr_accessor :email_from_name

    # Channel: Email The email address the email is from. If not specified, will default to \"from email\" set in the OneSignal Dashboard Email Settings. 
    attr_accessor :email_from_address

    # Channel: Email The preheader text of the email. Preheader is the preview text displayed immediately after an email subject that provides additional context about the email content. If not specified, will default to null. 
    attr_accessor :email_preheader

    # Channel: Email Default is `false`. If set to `true`, the URLs sent within the email will not include link tracking and will be the same as originally set; otherwise, all the URLs in the email will be tracked.
    attr_accessor :disable_email_click_tracking

    # Channel: Email Default is `false`. This field is used to send transactional notifications. If set to `true`, this notification will also be sent to unsubscribed emails. If a `template_id` is provided, the `include_unsubscribed` value from the template will be inherited. If you are using a third-party ESP, this field requires the ESP's list of unsubscribed emails to be cleared.
    attr_accessor :include_unsubscribed

    # Channel: SMS Phone Number used to send SMS. Should be a registered Twilio phone number in E.164 format. 
    attr_accessor :sms_from

    # Channel: SMS URLs for the media files to be attached to the SMS content. Limit: 10 media urls with a total max. size of 5MBs. 
    attr_accessor :sms_media_urls

    attr_accessor :filters

    # Channel: All JSON object that can be used as a source of message personalization data for fields that support tag variable substitution. Push, SMS: Can accept up to 2048 bytes of valid JSON. Email: Can accept up to 10000 bytes of valid JSON. Example: {\"order_id\": 123, \"currency\": \"USD\", \"amount\": 25} 
    attr_accessor :custom_data

    # Number of notifications that were successfully delivered.
    attr_accessor :successful

    # Number of notifications that could not be delivered due to those devices being unsubscribed.
    attr_accessor :failed

    # Number of notifications that could not be delivered due to an error. You can find more information by viewing the notification in the dashboard.
    attr_accessor :errored

    # Number of users who have clicked / tapped on your notification.
    attr_accessor :converted

    # Confirmed Deliveries number of devices that received the push notification. Paid Feature Only. Free accounts will see 0.
    attr_accessor :received

    attr_accessor :outcomes

    # Number of notifications that have not been sent out yet. This can mean either our system is still processing the notification or you have delayed options set.
    attr_accessor :remaining

    # Unix timestamp indicating when the notification was created.
    attr_accessor :queued_at

    # Unix timestamp indicating when notification delivery should begin.
    attr_accessor :send_after

    # Unix timestamp indicating when notification delivery completed. The delivery duration from start to finish can be calculated with completed_at - send_after.
    attr_accessor :completed_at

    attr_accessor :platform_delivery_stats

    # Indicates whether the notification was canceled before it could be sent.
    attr_accessor :canceled

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'included_segments' => :'included_segments',
        :'excluded_segments' => :'excluded_segments',
        :'include_subscription_ids' => :'include_subscription_ids',
        :'include_email_tokens' => :'include_email_tokens',
        :'include_phone_numbers' => :'include_phone_numbers',
        :'include_ios_tokens' => :'include_ios_tokens',
        :'include_wp_wns_uris' => :'include_wp_wns_uris',
        :'include_amazon_reg_ids' => :'include_amazon_reg_ids',
        :'include_chrome_reg_ids' => :'include_chrome_reg_ids',
        :'include_chrome_web_reg_ids' => :'include_chrome_web_reg_ids',
        :'include_android_reg_ids' => :'include_android_reg_ids',
        :'include_aliases' => :'include_aliases',
        :'target_channel' => :'target_channel',
        :'id' => :'id',
        :'value' => :'value',
        :'name' => :'name',
        :'aggregation' => :'aggregation',
        :'is_ios' => :'isIos',
        :'is_android' => :'isAndroid',
        :'is_huawei' => :'isHuawei',
        :'is_any_web' => :'isAnyWeb',
        :'is_chrome_web' => :'isChromeWeb',
        :'is_firefox' => :'isFirefox',
        :'is_safari' => :'isSafari',
        :'is_wp_wns' => :'isWP_WNS',
        :'is_adm' => :'isAdm',
        :'is_chrome' => :'isChrome',
        :'app_id' => :'app_id',
        :'external_id' => :'external_id',
        :'idempotency_key' => :'idempotency_key',
        :'contents' => :'contents',
        :'headings' => :'headings',
        :'subtitle' => :'subtitle',
        :'data' => :'data',
        :'huawei_msg_type' => :'huawei_msg_type',
        :'url' => :'url',
        :'web_url' => :'web_url',
        :'app_url' => :'app_url',
        :'ios_attachments' => :'ios_attachments',
        :'template_id' => :'template_id',
        :'content_available' => :'content_available',
        :'mutable_content' => :'mutable_content',
        :'target_content_identifier' => :'target_content_identifier',
        :'big_picture' => :'big_picture',
        :'huawei_big_picture' => :'huawei_big_picture',
        :'adm_big_picture' => :'adm_big_picture',
        :'chrome_big_picture' => :'chrome_big_picture',
        :'chrome_web_image' => :'chrome_web_image',
        :'buttons' => :'buttons',
        :'web_buttons' => :'web_buttons',
        :'ios_category' => :'ios_category',
        :'android_channel_id' => :'android_channel_id',
        :'huawei_channel_id' => :'huawei_channel_id',
        :'existing_android_channel_id' => :'existing_android_channel_id',
        :'huawei_existing_channel_id' => :'huawei_existing_channel_id',
        :'android_background_layout' => :'android_background_layout',
        :'small_icon' => :'small_icon',
        :'huawei_small_icon' => :'huawei_small_icon',
        :'large_icon' => :'large_icon',
        :'huawei_large_icon' => :'huawei_large_icon',
        :'adm_small_icon' => :'adm_small_icon',
        :'adm_large_icon' => :'adm_large_icon',
        :'chrome_web_icon' => :'chrome_web_icon',
        :'chrome_web_badge' => :'chrome_web_badge',
        :'firefox_icon' => :'firefox_icon',
        :'chrome_icon' => :'chrome_icon',
        :'ios_sound' => :'ios_sound',
        :'android_sound' => :'android_sound',
        :'huawei_sound' => :'huawei_sound',
        :'adm_sound' => :'adm_sound',
        :'wp_wns_sound' => :'wp_wns_sound',
        :'android_led_color' => :'android_led_color',
        :'huawei_led_color' => :'huawei_led_color',
        :'android_accent_color' => :'android_accent_color',
        :'huawei_accent_color' => :'huawei_accent_color',
        :'android_visibility' => :'android_visibility',
        :'huawei_visibility' => :'huawei_visibility',
        :'ios_badge_type' => :'ios_badgeType',
        :'ios_badge_count' => :'ios_badgeCount',
        :'collapse_id' => :'collapse_id',
        :'web_push_topic' => :'web_push_topic',
        :'apns_alert' => :'apns_alert',
        :'delayed_option' => :'delayed_option',
        :'delivery_time_of_day' => :'delivery_time_of_day',
        :'ttl' => :'ttl',
        :'priority' => :'priority',
        :'apns_push_type_override' => :'apns_push_type_override',
        :'throttle_rate_per_minute' => :'throttle_rate_per_minute',
        :'android_group' => :'android_group',
        :'android_group_message' => :'android_group_message',
        :'adm_group' => :'adm_group',
        :'adm_group_message' => :'adm_group_message',
        :'thread_id' => :'thread_id',
        :'summary_arg' => :'summary_arg',
        :'summary_arg_count' => :'summary_arg_count',
        :'ios_relevance_score' => :'ios_relevance_score',
        :'ios_interruption_level' => :'ios_interruption_level',
        :'email_subject' => :'email_subject',
        :'email_body' => :'email_body',
        :'email_from_name' => :'email_from_name',
        :'email_from_address' => :'email_from_address',
        :'email_preheader' => :'email_preheader',
        :'disable_email_click_tracking' => :'disable_email_click_tracking',
        :'include_unsubscribed' => :'include_unsubscribed',
        :'sms_from' => :'sms_from',
        :'sms_media_urls' => :'sms_media_urls',
        :'filters' => :'filters',
        :'custom_data' => :'custom_data',
        :'successful' => :'successful',
        :'failed' => :'failed',
        :'errored' => :'errored',
        :'converted' => :'converted',
        :'received' => :'received',
        :'outcomes' => :'outcomes',
        :'remaining' => :'remaining',
        :'queued_at' => :'queued_at',
        :'send_after' => :'send_after',
        :'completed_at' => :'completed_at',
        :'platform_delivery_stats' => :'platform_delivery_stats',
        :'canceled' => :'canceled'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'included_segments' => :'Array<String>',
        :'excluded_segments' => :'Array<String>',
        :'include_subscription_ids' => :'Array<String>',
        :'include_email_tokens' => :'Array<String>',
        :'include_phone_numbers' => :'Array<String>',
        :'include_ios_tokens' => :'Array<String>',
        :'include_wp_wns_uris' => :'Array<String>',
        :'include_amazon_reg_ids' => :'Array<String>',
        :'include_chrome_reg_ids' => :'Array<String>',
        :'include_chrome_web_reg_ids' => :'Array<String>',
        :'include_android_reg_ids' => :'Array<String>',
        :'include_aliases' => :'Hash<String, Array<String>>',
        :'target_channel' => :'String',
        :'id' => :'String',
        :'value' => :'Integer',
        :'name' => :'String',
        :'aggregation' => :'String',
        :'is_ios' => :'Boolean',
        :'is_android' => :'Boolean',
        :'is_huawei' => :'Boolean',
        :'is_any_web' => :'Boolean',
        :'is_chrome_web' => :'Boolean',
        :'is_firefox' => :'Boolean',
        :'is_safari' => :'Boolean',
        :'is_wp_wns' => :'Boolean',
        :'is_adm' => :'Boolean',
        :'is_chrome' => :'Boolean',
        :'app_id' => :'String',
        :'external_id' => :'String',
        :'idempotency_key' => :'String',
        :'contents' => :'LanguageStringMap',
        :'headings' => :'LanguageStringMap',
        :'subtitle' => :'LanguageStringMap',
        :'data' => :'Object',
        :'huawei_msg_type' => :'String',
        :'url' => :'String',
        :'web_url' => :'String',
        :'app_url' => :'String',
        :'ios_attachments' => :'Object',
        :'template_id' => :'String',
        :'content_available' => :'Boolean',
        :'mutable_content' => :'Boolean',
        :'target_content_identifier' => :'String',
        :'big_picture' => :'String',
        :'huawei_big_picture' => :'String',
        :'adm_big_picture' => :'String',
        :'chrome_big_picture' => :'String',
        :'chrome_web_image' => :'String',
        :'buttons' => :'Array<Button>',
        :'web_buttons' => :'Array<WebButton>',
        :'ios_category' => :'String',
        :'android_channel_id' => :'String',
        :'huawei_channel_id' => :'String',
        :'existing_android_channel_id' => :'String',
        :'huawei_existing_channel_id' => :'String',
        :'android_background_layout' => :'BasicNotificationAllOfAndroidBackgroundLayout',
        :'small_icon' => :'String',
        :'huawei_small_icon' => :'String',
        :'large_icon' => :'String',
        :'huawei_large_icon' => :'String',
        :'adm_small_icon' => :'String',
        :'adm_large_icon' => :'String',
        :'chrome_web_icon' => :'String',
        :'chrome_web_badge' => :'String',
        :'firefox_icon' => :'String',
        :'chrome_icon' => :'String',
        :'ios_sound' => :'String',
        :'android_sound' => :'String',
        :'huawei_sound' => :'String',
        :'adm_sound' => :'String',
        :'wp_wns_sound' => :'String',
        :'android_led_color' => :'String',
        :'huawei_led_color' => :'String',
        :'android_accent_color' => :'String',
        :'huawei_accent_color' => :'String',
        :'android_visibility' => :'Integer',
        :'huawei_visibility' => :'Integer',
        :'ios_badge_type' => :'String',
        :'ios_badge_count' => :'Integer',
        :'collapse_id' => :'String',
        :'web_push_topic' => :'String',
        :'apns_alert' => :'Object',
        :'delayed_option' => :'String',
        :'delivery_time_of_day' => :'String',
        :'ttl' => :'Integer',
        :'priority' => :'Integer',
        :'apns_push_type_override' => :'String',
        :'throttle_rate_per_minute' => :'Integer',
        :'android_group' => :'String',
        :'android_group_message' => :'String',
        :'adm_group' => :'String',
        :'adm_group_message' => :'Object',
        :'thread_id' => :'String',
        :'summary_arg' => :'String',
        :'summary_arg_count' => :'Integer',
        :'ios_relevance_score' => :'Float',
        :'ios_interruption_level' => :'String',
        :'email_subject' => :'String',
        :'email_body' => :'String',
        :'email_from_name' => :'String',
        :'email_from_address' => :'String',
        :'email_preheader' => :'String',
        :'disable_email_click_tracking' => :'Boolean',
        :'include_unsubscribed' => :'Boolean',
        :'sms_from' => :'String',
        :'sms_media_urls' => :'Array<String>',
        :'filters' => :'Array<FilterExpression>',
        :'custom_data' => :'Object',
        :'successful' => :'Integer',
        :'failed' => :'Integer',
        :'errored' => :'Integer',
        :'converted' => :'Integer',
        :'received' => :'Integer',
        :'outcomes' => :'Array<OutcomeData>',
        :'remaining' => :'Integer',
        :'queued_at' => :'Integer',
        :'send_after' => :'Integer',
        :'completed_at' => :'Integer',
        :'platform_delivery_stats' => :'PlatformDeliveryData',
        :'canceled' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'include_subscription_ids',
        :'include_aliases',
        :'name',
        :'is_ios',
        :'is_android',
        :'is_huawei',
        :'is_any_web',
        :'is_chrome_web',
        :'is_firefox',
        :'is_safari',
        :'is_wp_wns',
        :'is_adm',
        :'is_chrome',
        :'external_id',
        :'idempotency_key',
        :'contents',
        :'headings',
        :'subtitle',
        :'data',
        :'huawei_msg_type',
        :'url',
        :'web_url',
        :'app_url',
        :'ios_attachments',
        :'template_id',
        :'content_available',
        :'target_content_identifier',
        :'big_picture',
        :'huawei_big_picture',
        :'adm_big_picture',
        :'chrome_big_picture',
        :'chrome_web_image',
        :'buttons',
        :'web_buttons',
        :'ios_category',
        :'huawei_channel_id',
        :'huawei_existing_channel_id',
        :'small_icon',
        :'huawei_small_icon',
        :'large_icon',
        :'huawei_large_icon',
        :'adm_small_icon',
        :'adm_large_icon',
        :'chrome_web_icon',
        :'chrome_web_badge',
        :'firefox_icon',
        :'chrome_icon',
        :'ios_sound',
        :'android_sound',
        :'huawei_sound',
        :'adm_sound',
        :'wp_wns_sound',
        :'android_led_color',
        :'huawei_led_color',
        :'android_accent_color',
        :'huawei_accent_color',
        :'android_visibility',
        :'huawei_visibility',
        :'ios_badge_type',
        :'ios_badge_count',
        :'web_push_topic',
        :'apns_alert',
        :'delayed_option',
        :'delivery_time_of_day',
        :'ttl',
        :'priority',
        :'throttle_rate_per_minute',
        :'android_group',
        :'android_group_message',
        :'adm_group',
        :'adm_group_message',
        :'thread_id',
        :'ios_relevance_score',
        :'ios_interruption_level',
        :'email_subject',
        :'email_from_name',
        :'email_from_address',
        :'email_preheader',
        :'disable_email_click_tracking',
        :'sms_from',
        :'sms_media_urls',
        :'filters',
        :'custom_data',
        :'received',
        :'send_after',
        :'completed_at',
      ])
    end

    # List of class defined in allOf (OpenAPI v3)
    def self.openapi_all_of
      [
      :'BasicNotification',
      :'DeliveryData',
      :'NotificationWithMetaAllOf',
      :'OutcomesData'
      ]
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OneSignal::NotificationWithMeta` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OneSignal::NotificationWithMeta`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'included_segments')
        if (value = attributes[:'included_segments']).is_a?(Array)
          self.included_segments = value
        end
      end

      if attributes.key?(:'excluded_segments')
        if (value = attributes[:'excluded_segments']).is_a?(Array)
          self.excluded_segments = value
        end
      end

      if attributes.key?(:'include_subscription_ids')
        if (value = attributes[:'include_subscription_ids']).is_a?(Array)
          self.include_subscription_ids = value
        end
      end

      if attributes.key?(:'include_email_tokens')
        if (value = attributes[:'include_email_tokens']).is_a?(Array)
          self.include_email_tokens = value
        end
      end

      if attributes.key?(:'include_phone_numbers')
        if (value = attributes[:'include_phone_numbers']).is_a?(Array)
          self.include_phone_numbers = value
        end
      end

      if attributes.key?(:'include_ios_tokens')
        if (value = attributes[:'include_ios_tokens']).is_a?(Array)
          self.include_ios_tokens = value
        end
      end

      if attributes.key?(:'include_wp_wns_uris')
        if (value = attributes[:'include_wp_wns_uris']).is_a?(Array)
          self.include_wp_wns_uris = value
        end
      end

      if attributes.key?(:'include_amazon_reg_ids')
        if (value = attributes[:'include_amazon_reg_ids']).is_a?(Array)
          self.include_amazon_reg_ids = value
        end
      end

      if attributes.key?(:'include_chrome_reg_ids')
        if (value = attributes[:'include_chrome_reg_ids']).is_a?(Array)
          self.include_chrome_reg_ids = value
        end
      end

      if attributes.key?(:'include_chrome_web_reg_ids')
        if (value = attributes[:'include_chrome_web_reg_ids']).is_a?(Array)
          self.include_chrome_web_reg_ids = value
        end
      end

      if attributes.key?(:'include_android_reg_ids')
        if (value = attributes[:'include_android_reg_ids']).is_a?(Array)
          self.include_android_reg_ids = value
        end
      end

      if attributes.key?(:'include_aliases')
        if (value = attributes[:'include_aliases']).is_a?(Hash)
          self.include_aliases = value
        end
      end

      if attributes.key?(:'target_channel')
        self.target_channel = attributes[:'target_channel']
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'value')
        self.value = attributes[:'value']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'aggregation')
        self.aggregation = attributes[:'aggregation']
      end

      if attributes.key?(:'is_ios')
        self.is_ios = attributes[:'is_ios']
      end

      if attributes.key?(:'is_android')
        self.is_android = attributes[:'is_android']
      end

      if attributes.key?(:'is_huawei')
        self.is_huawei = attributes[:'is_huawei']
      end

      if attributes.key?(:'is_any_web')
        self.is_any_web = attributes[:'is_any_web']
      end

      if attributes.key?(:'is_chrome_web')
        self.is_chrome_web = attributes[:'is_chrome_web']
      end

      if attributes.key?(:'is_firefox')
        self.is_firefox = attributes[:'is_firefox']
      end

      if attributes.key?(:'is_safari')
        self.is_safari = attributes[:'is_safari']
      end

      if attributes.key?(:'is_wp_wns')
        self.is_wp_wns = attributes[:'is_wp_wns']
      end

      if attributes.key?(:'is_adm')
        self.is_adm = attributes[:'is_adm']
      end

      if attributes.key?(:'is_chrome')
        self.is_chrome = attributes[:'is_chrome']
      end

      if attributes.key?(:'app_id')
        self.app_id = attributes[:'app_id']
      end

      if attributes.key?(:'external_id')
        self.external_id = attributes[:'external_id']
      end

      if attributes.key?(:'idempotency_key')
        self.idempotency_key = attributes[:'idempotency_key']
      end

      if attributes.key?(:'contents')
        self.contents = attributes[:'contents']
      end

      if attributes.key?(:'headings')
        self.headings = attributes[:'headings']
      end

      if attributes.key?(:'subtitle')
        self.subtitle = attributes[:'subtitle']
      end

      if attributes.key?(:'data')
        self.data = attributes[:'data']
      end

      if attributes.key?(:'huawei_msg_type')
        self.huawei_msg_type = attributes[:'huawei_msg_type']
      end

      if attributes.key?(:'url')
        self.url = attributes[:'url']
      end

      if attributes.key?(:'web_url')
        self.web_url = attributes[:'web_url']
      end

      if attributes.key?(:'app_url')
        self.app_url = attributes[:'app_url']
      end

      if attributes.key?(:'ios_attachments')
        self.ios_attachments = attributes[:'ios_attachments']
      end

      if attributes.key?(:'template_id')
        self.template_id = attributes[:'template_id']
      end

      if attributes.key?(:'content_available')
        self.content_available = attributes[:'content_available']
      end

      if attributes.key?(:'mutable_content')
        self.mutable_content = attributes[:'mutable_content']
      end

      if attributes.key?(:'target_content_identifier')
        self.target_content_identifier = attributes[:'target_content_identifier']
      end

      if attributes.key?(:'big_picture')
        self.big_picture = attributes[:'big_picture']
      end

      if attributes.key?(:'huawei_big_picture')
        self.huawei_big_picture = attributes[:'huawei_big_picture']
      end

      if attributes.key?(:'adm_big_picture')
        self.adm_big_picture = attributes[:'adm_big_picture']
      end

      if attributes.key?(:'chrome_big_picture')
        self.chrome_big_picture = attributes[:'chrome_big_picture']
      end

      if attributes.key?(:'chrome_web_image')
        self.chrome_web_image = attributes[:'chrome_web_image']
      end

      if attributes.key?(:'buttons')
        if (value = attributes[:'buttons']).is_a?(Array)
          self.buttons = value
        end
      end

      if attributes.key?(:'web_buttons')
        if (value = attributes[:'web_buttons']).is_a?(Array)
          self.web_buttons = value
        end
      end

      if attributes.key?(:'ios_category')
        self.ios_category = attributes[:'ios_category']
      end

      if attributes.key?(:'android_channel_id')
        self.android_channel_id = attributes[:'android_channel_id']
      end

      if attributes.key?(:'huawei_channel_id')
        self.huawei_channel_id = attributes[:'huawei_channel_id']
      end

      if attributes.key?(:'existing_android_channel_id')
        self.existing_android_channel_id = attributes[:'existing_android_channel_id']
      end

      if attributes.key?(:'huawei_existing_channel_id')
        self.huawei_existing_channel_id = attributes[:'huawei_existing_channel_id']
      end

      if attributes.key?(:'android_background_layout')
        self.android_background_layout = attributes[:'android_background_layout']
      end

      if attributes.key?(:'small_icon')
        self.small_icon = attributes[:'small_icon']
      end

      if attributes.key?(:'huawei_small_icon')
        self.huawei_small_icon = attributes[:'huawei_small_icon']
      end

      if attributes.key?(:'large_icon')
        self.large_icon = attributes[:'large_icon']
      end

      if attributes.key?(:'huawei_large_icon')
        self.huawei_large_icon = attributes[:'huawei_large_icon']
      end

      if attributes.key?(:'adm_small_icon')
        self.adm_small_icon = attributes[:'adm_small_icon']
      end

      if attributes.key?(:'adm_large_icon')
        self.adm_large_icon = attributes[:'adm_large_icon']
      end

      if attributes.key?(:'chrome_web_icon')
        self.chrome_web_icon = attributes[:'chrome_web_icon']
      end

      if attributes.key?(:'chrome_web_badge')
        self.chrome_web_badge = attributes[:'chrome_web_badge']
      end

      if attributes.key?(:'firefox_icon')
        self.firefox_icon = attributes[:'firefox_icon']
      end

      if attributes.key?(:'chrome_icon')
        self.chrome_icon = attributes[:'chrome_icon']
      end

      if attributes.key?(:'ios_sound')
        self.ios_sound = attributes[:'ios_sound']
      end

      if attributes.key?(:'android_sound')
        self.android_sound = attributes[:'android_sound']
      end

      if attributes.key?(:'huawei_sound')
        self.huawei_sound = attributes[:'huawei_sound']
      end

      if attributes.key?(:'adm_sound')
        self.adm_sound = attributes[:'adm_sound']
      end

      if attributes.key?(:'wp_wns_sound')
        self.wp_wns_sound = attributes[:'wp_wns_sound']
      end

      if attributes.key?(:'android_led_color')
        self.android_led_color = attributes[:'android_led_color']
      end

      if attributes.key?(:'huawei_led_color')
        self.huawei_led_color = attributes[:'huawei_led_color']
      end

      if attributes.key?(:'android_accent_color')
        self.android_accent_color = attributes[:'android_accent_color']
      end

      if attributes.key?(:'huawei_accent_color')
        self.huawei_accent_color = attributes[:'huawei_accent_color']
      end

      if attributes.key?(:'android_visibility')
        self.android_visibility = attributes[:'android_visibility']
      end

      if attributes.key?(:'huawei_visibility')
        self.huawei_visibility = attributes[:'huawei_visibility']
      end

      if attributes.key?(:'ios_badge_type')
        self.ios_badge_type = attributes[:'ios_badge_type']
      end

      if attributes.key?(:'ios_badge_count')
        self.ios_badge_count = attributes[:'ios_badge_count']
      end

      if attributes.key?(:'collapse_id')
        self.collapse_id = attributes[:'collapse_id']
      end

      if attributes.key?(:'web_push_topic')
        self.web_push_topic = attributes[:'web_push_topic']
      end

      if attributes.key?(:'apns_alert')
        self.apns_alert = attributes[:'apns_alert']
      end

      if attributes.key?(:'delayed_option')
        self.delayed_option = attributes[:'delayed_option']
      end

      if attributes.key?(:'delivery_time_of_day')
        self.delivery_time_of_day = attributes[:'delivery_time_of_day']
      end

      if attributes.key?(:'ttl')
        self.ttl = attributes[:'ttl']
      end

      if attributes.key?(:'priority')
        self.priority = attributes[:'priority']
      end

      if attributes.key?(:'apns_push_type_override')
        self.apns_push_type_override = attributes[:'apns_push_type_override']
      end

      if attributes.key?(:'throttle_rate_per_minute')
        self.throttle_rate_per_minute = attributes[:'throttle_rate_per_minute']
      end

      if attributes.key?(:'android_group')
        self.android_group = attributes[:'android_group']
      end

      if attributes.key?(:'android_group_message')
        self.android_group_message = attributes[:'android_group_message']
      end

      if attributes.key?(:'adm_group')
        self.adm_group = attributes[:'adm_group']
      end

      if attributes.key?(:'adm_group_message')
        self.adm_group_message = attributes[:'adm_group_message']
      end

      if attributes.key?(:'thread_id')
        self.thread_id = attributes[:'thread_id']
      end

      if attributes.key?(:'summary_arg')
        self.summary_arg = attributes[:'summary_arg']
      end

      if attributes.key?(:'summary_arg_count')
        self.summary_arg_count = attributes[:'summary_arg_count']
      end

      if attributes.key?(:'ios_relevance_score')
        self.ios_relevance_score = attributes[:'ios_relevance_score']
      end

      if attributes.key?(:'ios_interruption_level')
        self.ios_interruption_level = attributes[:'ios_interruption_level']
      end

      if attributes.key?(:'email_subject')
        self.email_subject = attributes[:'email_subject']
      end

      if attributes.key?(:'email_body')
        self.email_body = attributes[:'email_body']
      end

      if attributes.key?(:'email_from_name')
        self.email_from_name = attributes[:'email_from_name']
      end

      if attributes.key?(:'email_from_address')
        self.email_from_address = attributes[:'email_from_address']
      end

      if attributes.key?(:'email_preheader')
        self.email_preheader = attributes[:'email_preheader']
      end

      if attributes.key?(:'disable_email_click_tracking')
        self.disable_email_click_tracking = attributes[:'disable_email_click_tracking']
      end

      if attributes.key?(:'include_unsubscribed')
        self.include_unsubscribed = attributes[:'include_unsubscribed']
      end

      if attributes.key?(:'sms_from')
        self.sms_from = attributes[:'sms_from']
      end

      if attributes.key?(:'sms_media_urls')
        if (value = attributes[:'sms_media_urls']).is_a?(Array)
          self.sms_media_urls = value
        end
      end

      if attributes.key?(:'filters')
        if (value = attributes[:'filters']).is_a?(Array)
          self.filters = value
        end
      end

      if attributes.key?(:'custom_data')
        self.custom_data = attributes[:'custom_data']
      end

      if attributes.key?(:'successful')
        self.successful = attributes[:'successful']
      end

      if attributes.key?(:'failed')
        self.failed = attributes[:'failed']
      end

      if attributes.key?(:'errored')
        self.errored = attributes[:'errored']
      end

      if attributes.key?(:'converted')
        self.converted = attributes[:'converted']
      end

      if attributes.key?(:'received')
        self.received = attributes[:'received']
      end

      if attributes.key?(:'outcomes')
        if (value = attributes[:'outcomes']).is_a?(Array)
          self.outcomes = value
        end
      end

      if attributes.key?(:'remaining')
        self.remaining = attributes[:'remaining']
      end

      if attributes.key?(:'queued_at')
        self.queued_at = attributes[:'queued_at']
      end

      if attributes.key?(:'send_after')
        self.send_after = attributes[:'send_after']
      end

      if attributes.key?(:'completed_at')
        self.completed_at = attributes[:'completed_at']
      end

      if attributes.key?(:'platform_delivery_stats')
        self.platform_delivery_stats = attributes[:'platform_delivery_stats']
      end

      if attributes.key?(:'canceled')
        self.canceled = attributes[:'canceled']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @app_id.nil?
        invalid_properties.push('invalid value for "app_id", app_id cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      target_channel_validator = EnumAttributeValidator.new('String', ["push", "email", "sms"])
      return false unless target_channel_validator.valid?(@target_channel)
      aggregation_validator = EnumAttributeValidator.new('String', ["sum", "count"])
      return false unless aggregation_validator.valid?(@aggregation)
      return false if @app_id.nil?
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] target_channel Object to be assigned
    def target_channel=(target_channel)
      validator = EnumAttributeValidator.new('String', ["push", "email", "sms"])
      unless validator.valid?(target_channel)
        fail ArgumentError, "invalid value for \"target_channel\", must be one of #{validator.allowable_values}."
      end
      @target_channel = target_channel
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] aggregation Object to be assigned
    def aggregation=(aggregation)
      validator = EnumAttributeValidator.new('String', ["sum", "count"])
      unless validator.valid?(aggregation)
        fail ArgumentError, "invalid value for \"aggregation\", must be one of #{validator.allowable_values}."
      end
      @aggregation = aggregation
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          included_segments == o.included_segments &&
          excluded_segments == o.excluded_segments &&
          include_subscription_ids == o.include_subscription_ids &&
          include_email_tokens == o.include_email_tokens &&
          include_phone_numbers == o.include_phone_numbers &&
          include_ios_tokens == o.include_ios_tokens &&
          include_wp_wns_uris == o.include_wp_wns_uris &&
          include_amazon_reg_ids == o.include_amazon_reg_ids &&
          include_chrome_reg_ids == o.include_chrome_reg_ids &&
          include_chrome_web_reg_ids == o.include_chrome_web_reg_ids &&
          include_android_reg_ids == o.include_android_reg_ids &&
          include_aliases == o.include_aliases &&
          target_channel == o.target_channel &&
          id == o.id &&
          value == o.value &&
          name == o.name &&
          aggregation == o.aggregation &&
          is_ios == o.is_ios &&
          is_android == o.is_android &&
          is_huawei == o.is_huawei &&
          is_any_web == o.is_any_web &&
          is_chrome_web == o.is_chrome_web &&
          is_firefox == o.is_firefox &&
          is_safari == o.is_safari &&
          is_wp_wns == o.is_wp_wns &&
          is_adm == o.is_adm &&
          is_chrome == o.is_chrome &&
          app_id == o.app_id &&
          external_id == o.external_id &&
          idempotency_key == o.idempotency_key &&
          contents == o.contents &&
          headings == o.headings &&
          subtitle == o.subtitle &&
          data == o.data &&
          huawei_msg_type == o.huawei_msg_type &&
          url == o.url &&
          web_url == o.web_url &&
          app_url == o.app_url &&
          ios_attachments == o.ios_attachments &&
          template_id == o.template_id &&
          content_available == o.content_available &&
          mutable_content == o.mutable_content &&
          target_content_identifier == o.target_content_identifier &&
          big_picture == o.big_picture &&
          huawei_big_picture == o.huawei_big_picture &&
          adm_big_picture == o.adm_big_picture &&
          chrome_big_picture == o.chrome_big_picture &&
          chrome_web_image == o.chrome_web_image &&
          buttons == o.buttons &&
          web_buttons == o.web_buttons &&
          ios_category == o.ios_category &&
          android_channel_id == o.android_channel_id &&
          huawei_channel_id == o.huawei_channel_id &&
          existing_android_channel_id == o.existing_android_channel_id &&
          huawei_existing_channel_id == o.huawei_existing_channel_id &&
          android_background_layout == o.android_background_layout &&
          small_icon == o.small_icon &&
          huawei_small_icon == o.huawei_small_icon &&
          large_icon == o.large_icon &&
          huawei_large_icon == o.huawei_large_icon &&
          adm_small_icon == o.adm_small_icon &&
          adm_large_icon == o.adm_large_icon &&
          chrome_web_icon == o.chrome_web_icon &&
          chrome_web_badge == o.chrome_web_badge &&
          firefox_icon == o.firefox_icon &&
          chrome_icon == o.chrome_icon &&
          ios_sound == o.ios_sound &&
          android_sound == o.android_sound &&
          huawei_sound == o.huawei_sound &&
          adm_sound == o.adm_sound &&
          wp_wns_sound == o.wp_wns_sound &&
          android_led_color == o.android_led_color &&
          huawei_led_color == o.huawei_led_color &&
          android_accent_color == o.android_accent_color &&
          huawei_accent_color == o.huawei_accent_color &&
          android_visibility == o.android_visibility &&
          huawei_visibility == o.huawei_visibility &&
          ios_badge_type == o.ios_badge_type &&
          ios_badge_count == o.ios_badge_count &&
          collapse_id == o.collapse_id &&
          web_push_topic == o.web_push_topic &&
          apns_alert == o.apns_alert &&
          delayed_option == o.delayed_option &&
          delivery_time_of_day == o.delivery_time_of_day &&
          ttl == o.ttl &&
          priority == o.priority &&
          apns_push_type_override == o.apns_push_type_override &&
          throttle_rate_per_minute == o.throttle_rate_per_minute &&
          android_group == o.android_group &&
          android_group_message == o.android_group_message &&
          adm_group == o.adm_group &&
          adm_group_message == o.adm_group_message &&
          thread_id == o.thread_id &&
          summary_arg == o.summary_arg &&
          summary_arg_count == o.summary_arg_count &&
          ios_relevance_score == o.ios_relevance_score &&
          ios_interruption_level == o.ios_interruption_level &&
          email_subject == o.email_subject &&
          email_body == o.email_body &&
          email_from_name == o.email_from_name &&
          email_from_address == o.email_from_address &&
          email_preheader == o.email_preheader &&
          disable_email_click_tracking == o.disable_email_click_tracking &&
          include_unsubscribed == o.include_unsubscribed &&
          sms_from == o.sms_from &&
          sms_media_urls == o.sms_media_urls &&
          filters == o.filters &&
          custom_data == o.custom_data &&
          successful == o.successful &&
          failed == o.failed &&
          errored == o.errored &&
          converted == o.converted &&
          received == o.received &&
          outcomes == o.outcomes &&
          remaining == o.remaining &&
          queued_at == o.queued_at &&
          send_after == o.send_after &&
          completed_at == o.completed_at &&
          platform_delivery_stats == o.platform_delivery_stats &&
          canceled == o.canceled
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [included_segments, excluded_segments, include_subscription_ids, include_email_tokens, include_phone_numbers, include_ios_tokens, include_wp_wns_uris, include_amazon_reg_ids, include_chrome_reg_ids, include_chrome_web_reg_ids, include_android_reg_ids, include_aliases, target_channel, id, value, name, aggregation, is_ios, is_android, is_huawei, is_any_web, is_chrome_web, is_firefox, is_safari, is_wp_wns, is_adm, is_chrome, app_id, external_id, idempotency_key, contents, headings, subtitle, data, huawei_msg_type, url, web_url, app_url, ios_attachments, template_id, content_available, mutable_content, target_content_identifier, big_picture, huawei_big_picture, adm_big_picture, chrome_big_picture, chrome_web_image, buttons, web_buttons, ios_category, android_channel_id, huawei_channel_id, existing_android_channel_id, huawei_existing_channel_id, android_background_layout, small_icon, huawei_small_icon, large_icon, huawei_large_icon, adm_small_icon, adm_large_icon, chrome_web_icon, chrome_web_badge, firefox_icon, chrome_icon, ios_sound, android_sound, huawei_sound, adm_sound, wp_wns_sound, android_led_color, huawei_led_color, android_accent_color, huawei_accent_color, android_visibility, huawei_visibility, ios_badge_type, ios_badge_count, collapse_id, web_push_topic, apns_alert, delayed_option, delivery_time_of_day, ttl, priority, apns_push_type_override, throttle_rate_per_minute, android_group, android_group_message, adm_group, adm_group_message, thread_id, summary_arg, summary_arg_count, ios_relevance_score, ios_interruption_level, email_subject, email_body, email_from_name, email_from_address, email_preheader, disable_email_click_tracking, include_unsubscribed, sms_from, sms_media_urls, filters, custom_data, successful, failed, errored, converted, received, outcomes, remaining, queued_at, send_after, completed_at, platform_delivery_stats, canceled].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OneSignal.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
