=begin
#OneSignal

#A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com

The version of the OpenAPI document: 1.0.2
Contact: devrel@onesignal.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OneSignal::BasicNotificationAllOfAndroidBackgroundLayout
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OneSignal::BasicNotificationAllOfAndroidBackgroundLayout do
  let(:instance) { OneSignal::BasicNotificationAllOfAndroidBackgroundLayout.new }

  describe 'test an instance of BasicNotificationAllOfAndroidBackgroundLayout' do
    it 'should create an instance of BasicNotificationAllOfAndroidBackgroundLayout' do
      expect(instance).to be_instance_of(OneSignal::BasicNotificationAllOfAndroidBackgroundLayout)
    end
  end
  describe 'test attribute "image"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "headings_color"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "contents_color"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
