=begin
#OneSignal

#A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com

The version of the OpenAPI document: 5.3.0
Contact: devrel@onesignal.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OneSignal::CopyTemplateRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OneSignal::CopyTemplateRequest do
  let(:instance) { OneSignal::CopyTemplateRequest.new }

  describe 'test an instance of CopyTemplateRequest' do
    it 'should create an instance of CopyTemplateRequest' do
      expect(instance).to be_instance_of(OneSignal::CopyTemplateRequest)
    end
  end
  describe 'test attribute "target_app_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
