=begin
#OneSignal

#A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com

The version of the OpenAPI document: 5.3.0
Contact: devrel@onesignal.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OneSignal::CreateApiKeyRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OneSignal::CreateApiKeyRequest do
  let(:instance) { OneSignal::CreateApiKeyRequest.new }

  describe 'test an instance of CreateApiKeyRequest' do
    it 'should create an instance of CreateApiKeyRequest' do
      expect(instance).to be_instance_of(OneSignal::CreateApiKeyRequest)
    end
  end
  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "ip_allowlist_mode"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["disabled", "explicit"])
      # validator.allowable_values.each do |value|
      #   expect { instance.ip_allowlist_mode = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "ip_allowlist"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
