=begin
#OneSignal

#A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com

The version of the OpenAPI document: 1.2.2
Contact: devrel@onesignal.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OneSignal::DeletePlayerNotFoundResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OneSignal::DeletePlayerNotFoundResponse do
  let(:instance) { OneSignal::DeletePlayerNotFoundResponse.new }

  describe 'test an instance of DeletePlayerNotFoundResponse' do
    it 'should create an instance of DeletePlayerNotFoundResponse' do
      expect(instance).to be_instance_of(OneSignal::DeletePlayerNotFoundResponse)
    end
  end
  describe 'test attribute "success"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
