=begin
#OneSignal

#A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com

Contact: devrel@onesignal.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OneSignal::EmailWarmUpRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OneSignal::EmailWarmUpRequest do
  let(:instance) { OneSignal::EmailWarmUpRequest.new }

  describe 'test an instance of EmailWarmUpRequest' do
    it 'should create an instance of EmailWarmUpRequest' do
      expect(instance).to be_instance_of(OneSignal::EmailWarmUpRequest)
    end
  end
  describe 'test attribute "stages"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "strategy"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["recommended", "custom"])
      # validator.allowable_values.each do |value|
      #   expect { instance.strategy = value }.not_to raise_error
      # end
    end
  end

end
