=begin
#OneSignal

#A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com

Contact: devrel@onesignal.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OneSignal::EstimateNotificationRecipientsRequestAllOf
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OneSignal::EstimateNotificationRecipientsRequestAllOf do
  let(:instance) { OneSignal::EstimateNotificationRecipientsRequestAllOf.new }

  describe 'test an instance of EstimateNotificationRecipientsRequestAllOf' do
    it 'should create an instance of EstimateNotificationRecipientsRequestAllOf' do
      expect(instance).to be_instance_of(OneSignal::EstimateNotificationRecipientsRequestAllOf)
    end
  end
  describe 'test attribute "app_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "filters"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "include_aliases"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "target_channel"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["push", "email", "sms"])
      # validator.allowable_values.each do |value|
      #   expect { instance.target_channel = value }.not_to raise_error
      # end
    end
  end

end
