=begin
#OneSignal

#A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com

Contact: devrel@onesignal.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OneSignal::JourneyReentryRules
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OneSignal::JourneyReentryRules do
  let(:instance) { OneSignal::JourneyReentryRules.new }

  describe 'test an instance of JourneyReentryRules' do
    it 'should create an instance of JourneyReentryRules' do
      expect(instance).to be_instance_of(OneSignal::JourneyReentryRules)
    end
  end
  describe 'test attribute "duration_seconds"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
