=begin
#OneSignal

#A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com

The version of the OpenAPI document: 5.2.0
Contact: devrel@onesignal.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OneSignal::SubscriptionBody
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OneSignal::SubscriptionBody do
  let(:instance) { OneSignal::SubscriptionBody.new }

  describe 'test an instance of SubscriptionBody' do
    it 'should create an instance of SubscriptionBody' do
      expect(instance).to be_instance_of(OneSignal::SubscriptionBody)
    end
  end
  describe 'test attribute "subscription"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
