=begin
#OneSignal

#A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com

The version of the OpenAPI document: 1.0.0
Contact: devrel@onesignal.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.0-SNAPSHOT

=end

# Common files
require 'onesignal/api_client'
require 'onesignal/api_error'
require 'onesignal/version'
require 'onesignal/configuration'

# Models
require 'onesignal/models/app'
require 'onesignal/models/button'
require 'onesignal/models/delivery_data'
require 'onesignal/models/export_players_request_body'
require 'onesignal/models/filter'
require 'onesignal/models/filter_expressions'
require 'onesignal/models/filter_notification_target'
require 'onesignal/models/get_notification_request_body'
require 'onesignal/models/inline_response200'
require 'onesignal/models/inline_response2001'
require 'onesignal/models/inline_response2002'
require 'onesignal/models/inline_response2003'
require 'onesignal/models/inline_response2004'
require 'onesignal/models/inline_response2005'
require 'onesignal/models/inline_response201'
require 'onesignal/models/inline_response400'
require 'onesignal/models/inline_response4001'
require 'onesignal/models/inline_response4002'
require 'onesignal/models/inline_response409'
require 'onesignal/models/notification'
require 'onesignal/models/notification_all_of'
require 'onesignal/models/notification_all_of_android_background_layout'
require 'onesignal/models/notification_slice'
require 'onesignal/models/notification_target'
require 'onesignal/models/operator'
require 'onesignal/models/outcome_data'
require 'onesignal/models/platform_delivery_data'
require 'onesignal/models/player'
require 'onesignal/models/player_notification_target'
require 'onesignal/models/player_slice'
require 'onesignal/models/purchase'
require 'onesignal/models/segment'
require 'onesignal/models/segment_notification_target'
require 'onesignal/models/string_map'
require 'onesignal/models/update_player_tags_request_body'

# APIs
require 'onesignal/api/default_api'

module OneSignal
  class << self
    # Customize default settings for the SDK using block.
    #   OneSignal.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
