=begin
#OneSignal

#A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com

The version of the OpenAPI document: 5.1.0
Contact: devrel@onesignal.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.0-SNAPSHOT

=end

# Common files
require 'onesignal/api_client'
require 'onesignal/api_error'
require 'onesignal/version'
require 'onesignal/configuration'

# Models
require 'onesignal/models/app'
require 'onesignal/models/basic_notification'
require 'onesignal/models/basic_notification_all_of'
require 'onesignal/models/basic_notification_all_of_android_background_layout'
require 'onesignal/models/button'
require 'onesignal/models/create_notification_success_response'
require 'onesignal/models/create_segment_conflict_response'
require 'onesignal/models/create_segment_success_response'
require 'onesignal/models/create_user_conflict_response'
require 'onesignal/models/create_user_conflict_response_errors_inner'
require 'onesignal/models/create_user_conflict_response_errors_items_meta'
require 'onesignal/models/delivery_data'
require 'onesignal/models/export_events_success_response'
require 'onesignal/models/export_subscriptions_request_body'
require 'onesignal/models/export_subscriptions_success_response'
require 'onesignal/models/filter'
require 'onesignal/models/filter_expression'
require 'onesignal/models/generic_error'
require 'onesignal/models/generic_success_bool_response'
require 'onesignal/models/get_notification_history_request_body'
require 'onesignal/models/get_segments_success_response'
require 'onesignal/models/language_string_map'
require 'onesignal/models/notification'
require 'onesignal/models/notification_all_of'
require 'onesignal/models/notification_history_success_response'
require 'onesignal/models/notification_slice'
require 'onesignal/models/notification_target'
require 'onesignal/models/notification_with_meta'
require 'onesignal/models/notification_with_meta_all_of'
require 'onesignal/models/operator'
require 'onesignal/models/outcome_data'
require 'onesignal/models/outcomes_data'
require 'onesignal/models/platform_delivery_data'
require 'onesignal/models/platform_delivery_data_email_all_of'
require 'onesignal/models/platform_delivery_data_sms_all_of'
require 'onesignal/models/properties_body'
require 'onesignal/models/properties_deltas'
require 'onesignal/models/properties_object'
require 'onesignal/models/purchase'
require 'onesignal/models/rate_limit_error'
require 'onesignal/models/segment'
require 'onesignal/models/segment_data'
require 'onesignal/models/segment_notification_target'
require 'onesignal/models/subscription'
require 'onesignal/models/subscription_body'
require 'onesignal/models/subscription_notification_target'
require 'onesignal/models/transfer_subscription_request_body'
require 'onesignal/models/update_live_activity_request'
require 'onesignal/models/update_live_activity_success_response'
require 'onesignal/models/update_user_request'
require 'onesignal/models/user'
require 'onesignal/models/user_identity_body'
require 'onesignal/models/web_button'

# APIs
require 'onesignal/api/default_api'

module OneSignal
  class << self
    # Customize default settings for the SDK using block.
    #   OneSignal.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
